const dummyCompanies = [
    {
      _id: '1',
      name: 'MedB Technologies',
      location: 'Kozhikode, Kerala',
      type: 'Healthcare SaaS',
      email: 'info@medb.in',
      contactNumber: '+91 98765 43210',
      logo: 'https://dummyimage.com/100x100/6366f1/ffffff&text=MB',
    },
    {
      _id: '2',
      name: 'Firstlook Innovations',
      location: 'Bengaluru, Karnataka',
      type: 'Dating Platform',
      email: 'contact@firstlook.com',
      contactNumber: '+91 99876 54321',
      logo: 'https://dummyimage.com/100x100/f59e0b/ffffff&text=FL',
    },
    {
      _id: '3',
      name: 'TechVibe Solutions',
      location: 'Chennai, Tamil Nadu',
      type: 'Software Services',
      email: 'hello@techvibe.io',
      contactNumber: '+91 91234 56789',
      logo: 'https://dummyimage.com/100x100/10b981/ffffff&text=TV',
    },
    {
      _id: '4',
      name: 'CloudBridge Systems',
      location: 'Mumbai, Maharashtra',
      type: 'Cloud Infrastructure',
      email: 'support@cloudbridge.in',
      contactNumber: '+91 92345 67891',
      logo: 'https://dummyimage.com/100x100/ef4444/ffffff&text=CB',
    },
    {
      _id: '5',
      name: 'ByteWave Technologies',
      location: 'Hyderabad, Telangana',
      type: 'Web & App Development',
      email: 'info@bytewave.com',
      contactNumber: '+91 93456 78912',
      logo: 'https://dummyimage.com/100x100/8b5cf6/ffffff&text=BW',
    },
    {
      _id: '6',
      name: 'NeoHealth Digital',
      location: 'Delhi NCR',
      type: 'Digital Health Solutions',
      email: 'care@neohealth.io',
      contactNumber: '+91 98765 32109',
      logo: 'https://dummyimage.com/100x100/f97316/ffffff&text=NH',
    },
    {
      _id: '7',
      name: 'NextEdge Analytics',
      location: 'Pune, Maharashtra',
      type: 'Data Analytics',
      email: 'info@nextedge.ai',
      contactNumber: '+91 98654 21098',
      logo: 'https://dummyimage.com/100x100/22c55e/ffffff&text=NE',
    },
    {
      _id: '8',
      name: 'Zynapse AI Labs',
      location: 'Kochi, Kerala',
      type: 'AI & ML Research',
      email: 'team@zynapse.ai',
      contactNumber: '+91 94567 89012',
      logo: 'https://dummyimage.com/100x100/3b82f6/ffffff&text=ZA',
    },
  ];
  
  export default dummyCompanies;